"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, RotateCcw, Ruler } from "lucide-react";
import type { MetrologyTool } from "../../../../lib/metrology/tools";

type Values = Record<string,string>;
const num=(v:string)=>Number(v);
const fmt=(v:number,d=6)=>Number.isFinite(v)?Number(v.toFixed(d)).toString():"—";

const configs: Record<string,{fields:[string,string,string?][]; calc:(v:Values)=>[string,string][]}> = {
 "tolerance-calculator": { fields:[["nominal","Nominal","10"],["plus","+ Tolerance","0.05"],["minus","- Tolerance","0.05"]], calc:v=>[["Upper Limit",fmt(num(v.nominal)+num(v.plus))],["Lower Limit",fmt(num(v.nominal)-num(v.minus))],["Total Tolerance",fmt(num(v.plus)+num(v.minus))]] },
 "measurement-statistics": { fields:[["values","Measurements (comma separated)","10.01, 10.02, 9.99, 10.00"]], calc:v=>{const a=v.values.split(/[,\s]+/).map(Number).filter(Number.isFinite);if(!a.length)return [["Result","—"]];const mean=a.reduce((x,y)=>x+y,0)/a.length;const sd=a.length>1?Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/(a.length-1)):0;return [["Count",String(a.length)],["Mean",fmt(mean)],["Std. Deviation",fmt(sd)],["Range",fmt(Math.max(...a)-Math.min(...a))],["Minimum",fmt(Math.min(...a))],["Maximum",fmt(Math.max(...a))]]} },
 "percent-error": { fields:[["measured","Measured Value","9.98"],["reference","Reference Value","10"]], calc:v=>[["Percent Error",fmt(Math.abs((num(v.measured)-num(v.reference))/num(v.reference))*100)+" %"],["Deviation",fmt(num(v.measured)-num(v.reference))]] },
 "percent-difference": { fields:[["a","Value A","10"],["b","Value B","10.2"]], calc:v=>[["Percent Difference",fmt(Math.abs(num(v.a)-num(v.b))/((Math.abs(num(v.a))+Math.abs(num(v.b)))/2)*100)+" %"],["Absolute Difference",fmt(Math.abs(num(v.a)-num(v.b)))]] },
 "capability-calculator": { fields:[["usl","Upper Spec Limit","10.1"],["lsl","Lower Spec Limit","9.9"],["mean","Process Mean","10.01"],["sd","Std. Deviation","0.02"]], calc:v=>{const cp=(num(v.usl)-num(v.lsl))/(6*num(v.sd));const cpk=Math.min((num(v.usl)-num(v.mean))/(3*num(v.sd)),(num(v.mean)-num(v.lsl))/(3*num(v.sd)));return [["Cp",fmt(cp,4)],["Cpk",fmt(cpk,4)]]} },
 "tur-calculator": { fields:[["tolerance","Total Tolerance","0.1"],["uncertainty","Expanded Uncertainty","0.025"]], calc:v=>[["TUR",fmt(num(v.tolerance)/num(v.uncertainty),3)+" : 1"]] },
 "uncertainty-calculator": { fields:[["values","Standard Uncertainties (comma separated)","0.01, 0.02, 0.005"],["k","Coverage Factor (k)","2"]], calc:v=>{const a=v.values.split(/[,\s]+/).map(Number).filter(Number.isFinite);const c=Math.sqrt(a.reduce((s,x)=>s+x*x,0));return [["Combined Standard Uncertainty",fmt(c)],["Expanded Uncertainty",fmt(c*num(v.k))]]} },
 "resolution-calculator": { fields:[["tolerance","Total Tolerance","0.1"],["resolution","Instrument Resolution","0.001"]], calc:v=>[["Tolerance / Resolution",fmt(num(v.tolerance)/num(v.resolution),2)+" : 1"],["Resolution % of Tolerance",fmt(num(v.resolution)/num(v.tolerance)*100,3)+" %"]] },
 "thermal-expansion": { fields:[["length","Original Length","100"],["cte","CTE (µm/m·°C)","11.5"],["deltaT","Temperature Change (°C)","5"]], calc:v=>{const change=num(v.length)*(num(v.cte)*1e-6)*num(v.deltaT);return [["Length Change",fmt(change)],["Final Length",fmt(num(v.length)+change)]]} },
};

const units: Record<string,{items:[string,number][]; base:string}> = {
 "measurement-converter": {base:"m",items:[["mm",.001],["inch",.0254],["µm",.000001],["mil",.0000254],["m",1]]},
 "pressure-converter": {base:"Pa",items:[["Pa",1],["kPa",1000],["MPa",1e6],["bar",100000],["psi",6894.757293],["inHg",3386.389]]},
 "torque-converter": {base:"N·m",items:[["N·m",1],["lbf·ft",1.355817948],["lbf·in",.112984829],["kgf·cm",.0980665]]},
 "force-converter": {base:"N",items:[["N",1],["kN",1000],["lbf",4.4482216153],["kgf",9.80665]]},
};

function Converter({slug}:{slug:string}){const cfg=units[slug];const [value,setValue]=useState("1");const [from,setFrom]=useState(cfg.items[0][0]);const base=num(value)*(cfg.items.find(x=>x[0]===from)?.[1]||1);return <><div className="input-grid"><label><span>VALUE</span><input value={value} onChange={e=>setValue(e.target.value)}/></label><label><span>FROM UNIT</span><select value={from} onChange={e=>setFrom(e.target.value)}>{cfg.items.map(x=><option key={x[0]}>{x[0]}</option>)}</select></label></div><div className="results">{cfg.items.map(x=><div key={x[0]}><span>{x[0]}</span><strong>{fmt(base/x[1],8)}</strong></div>)}</div></>}
function Temperature(){const [v,setV]=useState("20");const [u,setU]=useState("°C");const c=u==="°C"?num(v):u==="°F"?(num(v)-32)*5/9:num(v)-273.15;return <><div className="input-grid"><label><span>VALUE</span><input value={v} onChange={e=>setV(e.target.value)}/></label><label><span>FROM UNIT</span><select value={u} onChange={e=>setU(e.target.value)}><option>°C</option><option>°F</option><option>K</option></select></label></div><div className="results"><div><span>°C</span><strong>{fmt(c,4)}</strong></div><div><span>°F</span><strong>{fmt(c*9/5+32,4)}</strong></div><div><span>K</span><strong>{fmt(c+273.15,4)}</strong></div></div></>}
function CalibrationInterval(){const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [months,setMonths]=useState("12");const due=useMemo(()=>{const d=new Date(date+"T12:00:00");if(isNaN(d.getTime()))return "—";d.setMonth(d.getMonth()+num(months));return d.toLocaleDateString()},[date,months]);return <><div className="input-grid"><label><span>CALIBRATION DATE</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>INTERVAL (MONTHS)</span><input value={months} onChange={e=>setMonths(e.target.value)}/></label></div><div className="results"><div><span>NEXT DUE DATE</span><strong>{due}</strong></div></div></>}

export default function MetrologyInstrument({tool}:{tool:MetrologyTool}){const cfg=configs[tool.slug];const initial=Object.fromEntries((cfg?.fields||[]).map(f=>[f[0],f[2]||""]));const [values,setValues]=useState<Values>(initial);const results=cfg?cfg.calc(values):[];return <main className="tool-shell"><section className="tool-panel"><header className="tool-header"><div><span>METROLOGY TOOLKIT // {tool.category}</span><h1><Ruler size={19}/>{tool.name}</h1><p>{tool.description}</p></div><a href="/toolkits/metrology"><ArrowLeft size={13}/> TOOL LIBRARY</a></header><div className="tool-display"><span>INSTRUMENT STATUS</span><strong>READY // INPUT VALUES</strong></div><section className="instrument"><div className="instrument-title"><span>CONTROL INPUT</span><button onClick={()=>setValues(initial)}><RotateCcw size={11}/> RESET</button></div>{units[tool.slug]?<Converter slug={tool.slug}/>:tool.slug==="temperature-converter"?<Temperature/>:tool.slug==="calibration-interval"?<CalibrationInterval/>:<><div className="input-grid">{cfg?.fields.map(f=><label key={f[0]}><span>{f[1]}</span>{f[0]==="values"?<textarea value={values[f[0]]} onChange={e=>setValues({...values,[f[0]]:e.target.value})}/>:<input value={values[f[0]]} onChange={e=>setValues({...values,[f[0]]:e.target.value})}/>}</label>)}</div><div className="results">{results.map(r=><div key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong></div>)}</div></>}</section><p className="tool-note">CALCULATION AID // Verify applicable procedures, specifications, uncertainty budgets, and decision rules before using results for acceptance or calibration decisions.</p></section></main>}
