import Link from "next/link";
import { ArrowRight, CalendarDays, Clock3, Gift, MapPin, Star } from "lucide-react";
import type { BusinessSite } from "@/lib/business-site/data";
import { salonGallery, salonReviews, salonServices, salonStylists } from "./salonData";

function base(site:BusinessSite,preview:boolean){return preview?`/layouts/${site.layout.code}`:`/${site.instance.path_slug}`}
function Nav({site,preview}:{site:BusinessSite;preview:boolean}){const b=base(site,preview);return <header className="salon-nav salon-nav-editorial"><Link className="salon-wordmark" href={b}><strong>{site.instance.business_name}</strong><span>HAIR · COLOR · BRIDAL</span></Link><nav><Link href={`${b}/services`}>Services</Link><Link href={`${b}/team`}>Artists</Link><Link href={`${b}/gallery`}>Work</Link><Link href={`${b}/bridal`}>Bridal</Link><Link href={`${b}/about`}>Studio</Link><Link href={`${b}/contact`}>Contact</Link></nav><Link className="salon-book-top" href={`${b}/book`}>Reserve <ArrowRight size={14}/></Link></header>}
function Foot({site,preview}:{site:BusinessSite;preview:boolean}){const b=base(site,preview);return <footer className="salon-footer salon-footer-editorial"><div><strong>{site.instance.business_name}</strong><span>{site.content.address_text}</span></div><div><Link href={`${b}/gift-cards`}>Gift cards</Link><Link href={`${b}/book`}>Book</Link>{preview&&<Link href={`${b}/admin`}>Admin demo</Link>}</div></footer>}

export function SalonHome({site,preview}:{site:BusinessSite;preview:boolean}){const b=base(site,preview);return <main className="salon-site salon-editorial"><Nav site={site} preview={preview}/><section className="salon-editorial-hero"><div className="salon-editorial-copy"><span className="salon-script">Modern hair, personal to you.</span><h1>{site.content.headline}</h1><p>{site.content.subheadline}</p><div className="salon-editorial-actions"><Link className="salon-pill primary" href={`${b}/book`}><CalendarDays size={16}/>Book an appointment</Link><Link className="salon-text-link" href={`${b}/team`}>Meet the artists <ArrowRight size={15}/></Link></div><div className="salon-editorial-details"><div><Clock3/><span><b>Hours</b>{site.content.hours_text}</span></div><div><MapPin/><span><b>Visit us</b>{site.content.address_text}</span></div></div></div><div className="salon-editorial-images"><figure className="salon-image-main"><img src="https://images.pexels.com/photos/7755166/pexels-photo-7755166.jpeg?cs=srgb&dl=pexels-rdne-7755166.jpg&fm=jpg" alt="Stylist working with a client in a salon"/></figure><figure className="salon-image-float"><img src="https://images.pexels.com/photos/33867520/pexels-photo-33867520.jpeg?cs=srgb&dl=pexels-prolificpeople-33867520.jpg&fm=jpg" alt="Salon artist"/></figure><Link className="salon-consult-chip" href={`${b}/book?service=Consultation`}><small>NEW HERE?</small><strong>Start with a consultation</strong><ArrowRight size={16}/></Link></div></section><section className="salon-editorial-rail"><Link href={`${b}/services`}><span>01</span><strong>Services + pricing</strong></Link><Link href={`${b}/gallery`}><span>02</span><strong>See our work</strong></Link><Link href={`${b}/team`}><span>03</span><strong>Choose your artist</strong></Link><Link href={`${b}/bridal`}><span>04</span><strong>Bridal + events</strong></Link></section><Foot site={site} preview={preview}/></main>}

export function SalonServices({site,preview}:{site:BusinessSite;preview:boolean}){const b=base(site,preview);const groups=[...new Set(salonServices.map(s=>s.category))];return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><header className="salon-page-intro editorial"><span>THE MENU</span><h1>Beautiful work starts with the right appointment.</h1><p>Transparent starting prices, realistic timing, and a clear path into the right chair.</p></header><section className="salon-menu-editorial">{groups.map((group,index)=><section className="salon-menu-group" key={group}><div className="salon-menu-heading"><span>0{index+1}</span><h2>{group}</h2></div><div className="salon-menu-lines">{salonServices.filter(s=>s.category===group).map(s=><Link href={`${b}/book?service=${encodeURIComponent(s.name)}`} key={s.name}><div><strong>{s.name}</strong><p>{s.description}</p></div><aside><b>{s.price}</b><small>{s.duration}</small><ArrowRight size={15}/></aside></Link>)}</div></section>)}</section><Foot site={site} preview={preview}/></main>}

export function SalonTeam({site,preview}:{site:BusinessSite;preview:boolean}){const b=base(site,preview);return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><header className="salon-page-intro editorial"><span>THE ARTISTS</span><h1>Choose by specialty, energy, or the work you love.</h1><p>Every artist profile connects portfolio, specialties, eligible services, and live availability.</p></header><section className="salon-team-editorial">{salonStylists.map((s,i)=><article key={s.id} className={i%2?"reverse":""}><figure><img src={s.photo} alt={s.name}/><span>{String(i+1).padStart(2,"0")}</span></figure><div><small>{s.level}</small><h2>{s.name}</h2><p>{s.bio}</p><div className="salon-tag-line">{s.specialties.map(x=><span key={x}>{x}</span>)}</div><Link className="salon-pill" href={`${b}/book?stylist=${s.id}`}>Book with {s.name.split(" ")[0]} <ArrowRight size={15}/></Link></div></article>)}</section><Foot site={site} preview={preview}/></main>}

export function SalonGallery({site,preview}:{site:BusinessSite;preview:boolean}){return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><header className="salon-page-intro editorial"><span>SELECTED WORK</span><h1>Color, shape, texture, and the people behind it.</h1><p>Production gallery uploads can be tagged by artist, service, category and featured status.</p></header><section className="salon-gallery-editorial">{salonGallery.map((g,i)=><figure key={g.src} className={`g${i+1}`}><img src={g.src} alt={g.alt}/><figcaption><strong>{g.caption}</strong><span>{g.stylist}</span></figcaption></figure>)}</section><Foot site={site} preview={preview}/></main>}

export function SalonBridal({site,preview}:{site:BusinessSite;preview:boolean}){const b=base(site,preview);return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><section className="salon-bridal-editorial"><figure><img src="https://images.pexels.com/photos/33867543/pexels-photo-33867543.jpeg?cs=srgb&dl=pexels-prolificpeople-33867543.jpg&fm=jpg" alt="Bridal stylist portrait"/></figure><div><span>BRIDAL · EVENTS</span><h1>One calm plan for a very big day.</h1><p>Trials, inspiration, attendants, makeup, timing, travel and day-of notes live together instead of getting buried in email.</p><Link className="salon-pill primary" href={`${b}/bridal/inquiry`}>Begin a bridal inquiry <ArrowRight size={16}/></Link><ol><li><b>01</b><span><strong>Trial</strong><small>Save notes, photos and approved look.</small></span></li><li><b>02</b><span><strong>Party plan</strong><small>Services, artists and timing for every person.</small></span></li><li><b>03</b><span><strong>Wedding day</strong><small>One final schedule for salon, travel or venue.</small></span></li></ol></div></section><Foot site={site} preview={preview}/></main>}

export function SalonAbout({site,preview}:{site:BusinessSite;preview:boolean}){return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><section className="salon-about-editorial"><div className="salon-about-copy"><span>THE STUDIO</span><h1>A salon should feel personal before you ever sit down.</h1><p>{site.content.about_text}</p><blockquote>“{salonReviews[1].quote}”<cite>{salonReviews[1].name}</cite></blockquote></div><figure><img src="https://images.pexels.com/photos/7750099/pexels-photo-7750099.jpeg?cs=srgb&dl=pexels-artbovich-7750099.jpg&fm=jpg" alt="Salon interior"/></figure></section><Foot site={site} preview={preview}/></main>}

export function SalonContact({site,preview}:{site:BusinessSite;preview:boolean}){return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><section className="salon-contact-editorial"><div><span>CONTACT</span><h1>Need a human before you book?</h1><p>Send the studio a note. In production, messages land in the salon inbox and can attach to the client record later.</p><div className="salon-editorial-details stacked"><div><Clock3/><span><b>Hours</b>{site.content.hours_text}</span></div><div><MapPin/><span><b>Visit us</b>{site.content.address_text}</span></div></div></div><form><label>Your name<input placeholder="Name"/></label><label>Email<input type="email" placeholder="you@example.com"/></label><label>What can we help with?<select><option>General question</option><option>New client consultation</option><option>Existing appointment</option><option>Bridal</option><option>Extensions</option></select></label><label>Message<textarea rows={6} placeholder="Tell us what you need."/></label><button className="salon-pill primary">Send message <ArrowRight size={16}/></button><small>Demo only — nothing is sent.</small></form></section><Foot site={site} preview={preview}/></main>}

export function SalonGiftCards({site,preview}:{site:BusinessSite;preview:boolean}){return <main className="salon-site salon-editorial salon-page"><Nav site={site} preview={preview}/><section className="salon-gift-editorial"><div><Gift size={30}/><span>GIFT CARDS</span><h1>Give them an appointment worth looking forward to.</h1><p>Digital gift cards can be emailed, assigned to a client profile and redeemed at checkout.</p><div>{[50,100,150,250].map(v=><button key={v}>${v}</button>)}</div><button className="salon-pill primary">Preview checkout</button><small>Demo only — no payment is collected.</small></div></section><Foot site={site} preview={preview}/></main>}
