"use client";
import type { CSSProperties } from "react";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, BarChart3, Bell, CalendarDays, ChevronRight, Clock3, CreditCard, FileText, Gift, GripVertical, Image as ImageIcon, Inbox, LayoutDashboard, Megaphone, Menu, Package, Palette, Plus, Search, Settings, Sparkles, UserRound, Users, WalletCards, WandSparkles, Scissors } from "lucide-react";
import type { BusinessSite } from "@/lib/business-site/data";
import { salonServices, salonStylists } from "./salonData";

type Item={label:string;icon:any;badge?:string};
const itemsDefault:Item[]=[
 {label:"Dashboard",icon:LayoutDashboard},{label:"Appointments",icon:CalendarDays,badge:"18"},{label:"Calendar",icon:Clock3},{label:"Clients",icon:Users},{label:"Team",icon:UserRound},{label:"Services",icon:Scissors},{label:"Consultations",icon:Inbox,badge:"3"},{label:"Bridal Leads",icon:Sparkles,badge:"2"},{label:"Waitlist",icon:Clock3,badge:"5"},{label:"POS & Checkout",icon:CreditCard},{label:"Gift Cards",icon:Gift},{label:"Inventory",icon:Package},{label:"Marketing",icon:Megaphone},{label:"Reviews",icon:FileText},{label:"Gallery",icon:ImageIcon},{label:"Website",icon:Menu},{label:"Reports",icon:BarChart3},{label:"Appearance",icon:Palette},{label:"Settings",icon:Settings}
];

export default function SalonAdminDemo({site}:{site:BusinessSite}){
 const [active,setActive]=useState("Dashboard");const [items,setItems]=useState(itemsDefault);const [drag,setDrag]=useState<string|null>(null);const [target,setTarget]=useState<{label:string;position:"before"|"after"}|null>(null);const [width,setWidth]=useState(210);const [resizing,setResizing]=useState(false);
 const [accent,setAccent]=useState("#9f5b46");const [canvas,setCanvas]=useState("#f5f1ed");const [surface,setSurface]=useState("#ffffff");const [sidebar,setSidebar]=useState("#251f1c");
 useEffect(()=>{if(!resizing)return;const move=(e:MouseEvent)=>setWidth(Math.min(340,Math.max(176,e.clientX)));const up=()=>setResizing(false);window.addEventListener("mousemove",move);window.addEventListener("mouseup",up);return()=>{window.removeEventListener("mousemove",move);window.removeEventListener("mouseup",up)}},[resizing]);
 function reorder(source:string,dest:string,pos:"before"|"after"){if(source===dest)return;setItems(current=>{const n=[...current];const from=n.findIndex(i=>i.label===source);if(from<0)return current;const[m]=n.splice(from,1);let to=n.findIndex(i=>i.label===dest);if(pos==="after")to++;n.splice(to,0,m);return n});setTarget(null)}
 return <main className="salon-admin" style={{"--salon-admin-accent":accent,"--salon-admin-canvas":canvas,"--salon-admin-surface":surface,"--salon-admin-sidebar":sidebar,"--salon-admin-width":`${width}px`} as CSSProperties}><aside><div className="salon-admin-brand"><span><WandSparkles/></span><div><strong>{site.instance.business_name}</strong><small>Salon Console</small></div></div><nav>{items.map(item=>{const I=item.icon;return <button draggable onDragStart={()=>setDrag(item.label)} onDragEnd={()=>{setDrag(null);setTarget(null)}} onDragOver={e=>{e.preventDefault();if(!drag||drag===item.label)return;const r=e.currentTarget.getBoundingClientRect();setTarget({label:item.label,position:e.clientY<r.top+r.height/2?"before":"after"})}} onDrop={()=>drag&&target&&reorder(drag,item.label,target.position)} onClick={()=>setActive(item.label)} className={`${active===item.label?"active":""} ${target?.label===item.label?`drop-${target.position}`:""}`} key={item.label}><GripVertical className="drag"/><span><I size={17}/></span><b>{item.label}</b>{item.badge?<i>{item.badge}</i>:<ChevronRight size={14}/>}</button>})}</nav><Link href={`/layouts/${site.layout.code}`}><ArrowUpRight size={15}/> Public site</Link><button className="salon-admin-resize" onMouseDown={()=>setResizing(true)} aria-label="Resize sidebar"><i/></button></aside><section><header className="salon-admin-top"><div><span>SALON OPERATIONS</span><h1>{active}</h1></div><div><label><Search size={15}/><input placeholder="Search clients, services, bookings…"/></label><button><Bell/><i>4</i></button><button className="primary"><Plus/>New</button></div></header><div className="salon-admin-demo-note">Interactive sales demo · changes reset on refresh</div><SalonPanel active={active} accent={accent} setAccent={setAccent} canvas={canvas} setCanvas={setCanvas} surface={surface} setSurface={setSurface} sidebar={sidebar} setSidebar={setSidebar}/></section></main>
}

function SalonPanel({active,accent,setAccent,canvas,setCanvas,surface,setSurface,sidebar,setSidebar}:any){
 if(active==="Dashboard")return <div className="salon-admin-grid"><section className="salon-admin-hero"><div><span>TUESDAY · OCTOBER 6</span><h2>18 appointments. 4 chairs. One clear view.</h2><p>Booking, staff, clients and front-desk work stay connected to the same records.</p><div><button>Create appointment</button><button>Check out client</button></div></div><div><strong>$4,860</strong><span>Booked revenue today</span><small>82% chair utilization</small></div></section><Stat label="Appointments" value="18" note="15 confirmed"/><Stat label="Waitlist" value="5" note="2 match openings"/><Stat label="New clients" value="7" note="This week"/><Stat label="Rebooking" value="68%" note="+6% this month"/><section className="salon-admin-panel wide"><Title title="Today's salon" action="Open calendar"/><div className="salon-admin-schedule">{[["9:00","Ava","Dimensional Color","Erin Parker","Confirmed"],["10:30","Maya","Signature Cut + Finish","Leah Stone","Checked in"],["12:00","Jules","Balayage / Specialty Blonding","Morgan Lee","Confirmed"],["2:00","Noelle","Bridal Hair Trial","Samantha Reed","Deposit paid"],["4:30","Ava","Extension Consultation","Jamie Cole","New client"]].map(r=><div key={r.join()}><b>{r[0]}</b><span><strong>{r[2]}</strong><small>{r[3]} · {r[1]}</small></span><i>{r[4]}</i><button>Open</button></div>)}</div></section><section className="salon-admin-panel"><Title title="Front desk"/><div className="salon-quick-actions">{["Walk-in / quick sale","New consultation","Add to waitlist","Sell gift card","Upload portfolio","Send campaign"].map(x=><button key={x}>{x}<ArrowUpRight/></button>)}</div></section></div>;
 if(active==="Appointments")return <List title="Appointments" subtitle="Filter by status, stylist, service or client." rows={[["9:00 AM","Erin Parker","Dimensional Color · Ava","Confirmed"],["10:30 AM","Leah Stone","Signature Cut + Finish · Maya","Checked in"],["12:00 PM","Morgan Lee","Balayage · Jules","Confirmed"],["2:00 PM","Samantha Reed","Bridal Trial · Noelle","Deposit paid"]]}/>;
 if(active==="Calendar")return <Calendar/>;
 if(active==="Clients")return <List title="Client records" subtitle="History, formulas, notes, photos, preferences, purchases and upcoming appointments." rows={[["Erin Parker","Last visit Sep 12","Color formula saved","VIP"],["Morgan Lee","Last visit Aug 28","Balayage + toner","Returning"],["Jamie Cole","New client","Extension consultation","New"]]}/>;
 if(active==="Team")return <div className="salon-admin-card-grid">{salonStylists.map(s=><article key={s.id}><strong>{s.name}</strong><span>{s.level}</span><p>{s.specialties.join(" · ")}</p><div><button>Edit profile</button><button>Schedule</button></div></article>)}</div>;
 if(active==="Services")return <div className="salon-admin-panel"><Title title="Service catalog" action="Add service"/>{salonServices.map(s=><div className="salon-service-admin-row" key={s.name}><span><strong>{s.name}</strong><small>{s.category} · {s.description}</small></span><b>{s.duration}</b><b>{s.price}</b><button>Edit</button></div>)}</div>;
 if(active==="Consultations")return <List title="Consultations" subtitle="Color, extensions and corrective work that need review before booking." rows={[["Jamie Cole","Extensions","Photos attached","Needs quote"],["Riley West","Corrective color","New client","Needs stylist review"],["Nora James","Blonding","Consult complete","Ready to book"]]}/>;
 if(active==="Bridal Leads")return <List title="Bridal leads" subtitle="Wedding date, party size, services, trial status and day-of schedule." rows={[["Samantha Reed","May 16, 2027","Bride + 5 attendants","Trial booked"],["Olivia Grant","Jun 12, 2027","Bride + 3 attendants","Proposal sent"]]}/>;
 if(active==="Waitlist")return <List title="Waitlist" subtitle="Match cancellations and new openings against service duration and stylist eligibility." rows={[["Erin Parker","Dimensional Color","Ava or Jules","Tue/Thu after 3"],["Kate Bell","Signature Cut","First available","Any weekday"]]}/>;
 if(active==="POS & Checkout")return <div className="salon-pos"><section><Title title="Current ticket"/><div className="salon-ticket-row"><span>Signature Cut + Finish</span><b>$72</b></div><div className="salon-ticket-row"><span>Repair treatment add-on</span><b>$28</b></div><div className="salon-ticket-row"><span>Retail · Hydrating Mask</span><b>$36</b></div><div className="salon-ticket-total"><span>Total</span><strong>$136</strong></div><button>Take payment</button></section><section><Title title="Client"/><h3>Leah Stone</h3><p>1,240 loyalty points · Card on file · Next appointment not booked</p><button>Rebook before checkout</button></section></div>;
 if(active==="Gift Cards")return <List title="Gift cards" subtitle="Sell, email, redeem and track balances." rows={[["GC-1048","$150","Erin Parker","$72 remaining"],["GC-1052","$100","Morgan Lee","Unused"]]}/>;
 if(active==="Inventory")return <List title="Inventory" subtitle="Retail and back-bar product levels, reorder points and usage." rows={[["Hydrating Mask","Retail","7 on hand","Reorder at 4"],["20 vol developer","Back bar","2 on hand","LOW"],["Bond repair concentrate","Back bar","5 on hand","Healthy"]]}/>;
 if(active==="Marketing")return <div className="salon-admin-card-grid"><Action title="Fill tomorrow's openings" text="Send a targeted SMS to clients whose preferred services match open time."/><Action title="Rebook color guests" text="Find color clients past their normal return window and send a reminder."/><Action title="Birthday campaign" text="Automatically send a birthday offer to eligible clients this month."/><Action title="Review request" text="Send after completed appointments and track responses."/></div>;
 if(active==="Reviews")return <List title="Reviews" subtitle="Track reputation and request feedback after appointments." rows={[["Erin P.","5 stars","Google","Published"],["Morgan L.","5 stars","Google","Published"],["Anonymous","Private feedback","Follow up requested","Inbox"]]}/>;
 if(active==="Gallery")return <div className="salon-admin-panel"><Title title="Portfolio & before/after" action="Upload work"/><p>Upload images, tag the stylist and service, write alt text, and choose what appears on the public Gallery page.</p><div className="salon-upload-tiles">{["Add finished work","Add before / after","Add salon photo","Manage featured images"].map(x=><button key={x}><ImageIcon/><strong>{x}</strong></button>)}</div></div>;
 if(active==="Website")return <div className="salon-admin-form"><section><Title title="Homepage content"/><label>Headline<input defaultValue="Great hair starts with a conversation."/></label><label>Subheadline<textarea defaultValue="Cuts, dimensional color, extensions and bridal services—booked around the person in the chair."/></label><button>Preview changes</button></section><section><Title title="Public pages"/><div className="salon-page-toggle">{["Services","Team","Gallery","Bridal","Gift Cards","About","Contact"].map(x=><label key={x}><input type="checkbox" defaultChecked/>{x}</label>)}</div></section></div>;
 if(active==="Reports")return <div className="salon-admin-grid"><Stat label="Service revenue" value="$28.4K" note="This month"/><Stat label="Retail revenue" value="$4.8K" note="+12%"/><Stat label="Rebooking" value="68%" note="Target 72%"/><Stat label="No-show rate" value="2.4%" note="Down 0.8%"/><section className="salon-admin-panel wide"><Title title="Revenue by category"/>{[["Color",84],["Cuts & Styling",61],["Extensions",42],["Bridal",28],["Retail",22]].map(([x,v])=><div className="salon-report-bar" key={String(x)}><span>{x}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></div>)}</section></div>;
 if(active==="Appearance")return <div className="salon-admin-form"><section><Title title="Admin theme"/><Color label="Accent" value={accent} set={setAccent}/><Color label="Canvas" value={canvas} set={setCanvas}/><Color label="Cards" value={surface} set={setSurface}/><Color label="Sidebar" value={sidebar} set={setSidebar}/></section><section><Title title="Public Salon theme"/><p>Public-site theme controls would write into the layout palette in production. In this demo, use the presets below to visualize choices.</p><div className="salon-theme-presets">{[["Rosewood","#9f5b46","#f5eee6"],["Espresso","#6f4e37","#f4efe9"],["Sage","#65735b","#f0f2ec"],["Ink","#26272b","#f4f2ee"]].map(p=><button key={p[0]} onClick={()=>setAccent(p[1])}><i style={{background:p[1]}}/><span style={{background:p[2]}}/><b>{p[0]}</b></button>)}</div></section></div>;
 return <div className="salon-admin-form"><section><Title title="Salon settings"/><label>Salon name<input defaultValue="Mae & Moss Studio"/></label><label>Cancellation notice<select defaultValue="48"><option>24 hours</option><option value="48">48 hours</option><option>72 hours</option></select></label><label>Default deposit<select><option>No deposit</option><option>Card on file</option><option>$25 deposit</option><option>50% deposit</option></select></label><label><input type="checkbox" defaultChecked/> Allow online rescheduling</label><label><input type="checkbox" defaultChecked/> Enable waitlist matching</label><button>Save settings</button></section><section><Title title="Notifications"/><label><input type="checkbox" defaultChecked/> Appointment confirmations</label><label><input type="checkbox" defaultChecked/> SMS reminders</label><label><input type="checkbox" defaultChecked/> Rebooking reminders</label><label><input type="checkbox" defaultChecked/> Review requests</label></section></div>
}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <section className="salon-admin-stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></section>}
function Title({title,action}:{title:string;action?:string}){return <div className="salon-admin-title"><h2>{title}</h2>{action&&<button>{action}</button>}</div>}
function List({title,subtitle,rows}:{title:string;subtitle:string;rows:string[][]}){return <section className="salon-admin-panel"><Title title={title}/><p>{subtitle}</p><div className="salon-admin-list">{rows.map((r,i)=><div key={i}>{r.map((x,j)=><span key={j} className={j===0?"main":""}>{x}</span>)}<button>Open</button></div>)}</div></section>}
function Action({title,text}:{title:string;text:string}){return <article className="salon-action-card"><Megaphone/><h3>{title}</h3><p>{text}</p><button>Build campaign <ArrowUpRight/></button></article>}
function Color({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="salon-color"><span>{label}</span><input type="color" value={value} onChange={e=>set(e.target.value)}/><code>{value}</code></label>}
function Calendar(){return <section className="salon-admin-panel"><Title title="Week calendar" action="Today"/><div className="salon-calendar"><div className="head"></div>{["Tue 6","Wed 7","Thu 8","Fri 9","Sat 10"].map(d=><div className="head" key={d}>{d}</div>)}{["9 AM","10 AM","11 AM","12 PM","1 PM","2 PM","3 PM","4 PM"].map((t,i)=><div className="cal-row" key={t}><b>{t}</b>{[0,1,2,3,4].map(day=><span key={day}>{(i+day)%3===0?<i>Booked</i>:""}</span>)}</div>)}</div></section>}
